"""add old session number

Revision ID: 72b242bdec43
Revises: 2883dcbd3103
Create Date: 2024-06-23 23:07:46.734006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b242bdec43'
down_revision = '2883dcbd3103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_session_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('old_session_number')

    # ### end Alembic commands ###
